<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link https://moodledev.io/general/projects/api/amos}) using the
 * list of strings defined in public/install/stringnames.txt file.
 *
 * @package   installer
 * @license   https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['admindirname'] = 'Directorio de admin';
$string['availablelangs'] = 'Paccos de linguage disponibile';
$string['chooselanguagehead'] = 'Selige un linguage';
$string['databasehost'] = 'Hospite de base de datos';
$string['databasename'] = 'Nomine d ebase de datos';
$string['databasetypehead'] = 'Selige driver de base de datos';
$string['dataroot'] = 'Directorio de datos';
$string['datarootpermission'] = 'Permission de directorios de datos';
$string['dbprefix'] = 'Prefixo de tabella';
$string['dirroot'] = 'Directorio de Moodle';
$string['environmenthead'] = 'Verificante tu ambiente...';
$string['errorsinenvironment'] = 'Verifica de ambiente falleva!';
$string['installation'] = 'installation';
$string['paths'] = 'Percursos';
$string['pathshead'] = 'Confirma percursos';
$string['pathsrodataroot'] = 'Directorio de Dataroot non es scribibile.';
$string['pathsunsecuredataroot'] = 'Location de Dataroot non es secur';
$string['pathswrongadmindir'] = 'Directorio de admin non existe';
$string['phpversion'] = 'Version de PHP';
$string['webservernotconfigured'] = 'Servitor web non configurate';
$string['wwwroot'] = 'Adresse web';
