<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link https://moodledev.io/general/projects/api/amos}) using the
 * list of strings defined in public/install/stringnames.txt file.
 *
 * @package   installer
 * @license   https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['admindirname'] = 'Iùl-lann rianachd';
$string['availablelangs'] = 'Pacaichean cànain rim faotainn';
$string['chooselanguagehead'] = 'Tagh cànan';
$string['chooselanguagesub'] = 'Tagh cànan airson a’ chur an sàs.  Thèid an cànan seo a chleachdadh cuideachd mar chànan gnàthach na làraich, ged a dh’fhaodadh sin atharrachadh an dèidh làimh.';
$string['cliinstallheader'] = 'Prògram cur an sàs loidhne-àithne Mhoodle {$a}';
$string['clitablesexist'] = 'Tha clàran stòir-dàta ann mar-thà; chan urrainn cur an sàs CLI cumail air.';
$string['databasehost'] = 'Òstair stòir-dàta';
$string['databasename'] = 'Ainm stòir-dàta';
$string['databasetypehead'] = 'Tagh dràibhear an stòir-dàta';
$string['dataroot'] = 'Iùl-lann dàta';
$string['datarootpermission'] = 'Cead iùl-lannan dàta';
$string['dirroot'] = 'Iùl-lann Moodle';
$string['environmenthead'] = 'A’ sgrùdadh na h-àrainneachd agad...';
$string['errorsinenvironment'] = 'Dh’fhàillig an sgrùdadh àrainneachd!';
$string['installation'] = 'Cuir an sàs';
$string['langdownloaderror'] = 'Gu mì-fhortanach, cha b’ urrainn an cànan “{$a}) a luchdachadh a-nuas.  Cumaidh am pròiseas cur an sàs a’ dol ann am Beurla.';
$string['paths'] = 'Slighean';
$string['pathserrcreatedataroot'] = 'Chan urrainn an iùl-lann dàta ({$a->dataroot}) a chruthachadh leis an stàlaichear.';
$string['pathshead'] = 'Dearbh slighean';
$string['pathsrodataroot'] = 'Chan eil an iùl-lann freumh-dàta so-sgrìobhte.';
$string['pathsroparentdataroot'] = 'Chan eil an iùl-lann tuisteach ({$a->parent}) so-sgrìobhte.  Chan urrainn an iùl-lann dàta ({$a->dataroot}) a chruthachadh leis an stàlaichear.';
