name: Core

on:
  push:
    branches-ignore:
      - master
      - MOODLE_[0-9]+_STABLE
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+*

env:
  php: 8.2

jobs:
  Grunt:
    runs-on: ubuntu-22.04

    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Configuring node & npm
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Installing node stuff
        run: npm install

      - name: Running grunt
        run: npx grunt

      - name: Looking for uncommitted changes
        # Add all files to the git index and then run diff --cached to see all changes.
        # This ensures that we get the status of all files, including new files.
        # We ignore npm-shrinkwrap.json to make the tasks immune to npm changes.
        run: |
          git add .
          git reset -- npm-shrinkwrap.json
          git diff --cached --exit-code

  PHPUnit:
    name: PHPUnit (${{ matrix.db }}, ${{ matrix.ci_node_index }}/${{ matrix.ci_node_total }})
    runs-on: ${{ matrix.os }}
    services:
      exttests:
        image: moodlehq/moodle-exttests
        ports:
          - 8080:80
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        db: [mysqli, pgsql]
        ci_node_total: [ 4 ] # ci_node_index below needs to match with 1..N
        ci_node_index: [ 1, 2, 3, 4 ]
        include:
          # MySQL builds always run with the lowest PHP supported version.
          - os: ubuntu-22.04
            php: 8.0
            extensions:
            db: mysqli
          # PostgreSQL builds always run with the highest PHP supported version.
          - os: ubuntu-22.04
            php: 8.2
            db: pgsql

    steps:
      - name: Setting up DB mysql
        if: ${{ matrix.db == 'mysqli' }}
        uses: moodlehq/mysql-action@v1
        with:
          collation server: utf8mb4_bin
          mysql version: 8.0
          mysql database: test
          mysql user: test
          mysql password: test
          use tmpfs: true
          tmpfs size: '1024M'
          extra conf: --skip-log-bin

      - name: Setting up DB pgsql
        if: ${{ matrix.db == 'pgsql' }}
        uses: m4nu56/postgresql-action@v1
        with:
          postgresql version: 13
          postgresql db: test
          postgresql user: test
          postgresql password: test

      - name: Configuring git vars
        uses: rlespinasse/github-slug-action@v4

      - name: Setting up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          coverage: none

      - name: Checking out code from ${{ env.GITHUB_REF_SLUG }}
        uses: actions/checkout@v3

      - name: Setting up PHPUnit
        env:
          dbtype: ${{ matrix.db }}
        run: |
          echo "pathtophp=$(which php)" >> $GITHUB_ENV # Inject installed pathtophp to env. The template config needs it.
          cp .github/workflows/config-template.php config.php
          mkdir ../moodledata
          sudo locale-gen en_AU.UTF-8
          php admin/tool/phpunit/cli/init.php --no-composer-self-update

      - name: Running PHPUnit tests
        env:
          dbtype: ${{ matrix.db }}
          phpunit_options: ${{ secrets.phpunit_options }}
          ci_node_index: ${{ matrix.ci_node_index }}
          ci_node_total: ${{ matrix.ci_node_total }}
        run: |
          # Extract the test suites from each line
          mapfile -t test_suites < <(vendor/bin/phpunit --list-suites | grep ' - ' | sed -E 's/^ - (.+)$/\1/')

          # Split the test suites into equally sized chunks
          chunk_size=$(((${#test_suites[@]} + $ci_node_total - 1) / $ci_node_total))
          start_index=$((chunk_size * (ci_node_index - 1)))
          end_index=$((start_index + chunk_size))

          # Extract the test suites for the current node
          mapfile -t current_test_suites < <(echo "${test_suites[@]:$start_index:$end_index}")

          # Run the test suites for the current node
          vendor/bin/phpunit --testsuite "${current_test_suites[*]// /,}" $phpunit_options
